name: Build Android

on: push

jobs:
  build:
    name: Build
    runs-on: [self-hosted, research]

    steps:
      - uses: actions/checkout@v2

      - name: clone forest ci repository
        uses: actions/checkout@v2
        with:
          repository: philips-internal/forest-ci
          fetch-depth: 1
          path: .forest
          ref: feature/android-fastlane-action
          ssh-key: ${{ secrets.FOREST_CI_REPO_SSH_KEY }}

      - name: Build debug android application
        uses: ./.forest/actions/mobile/android-fastlane-action
        with:
          mode: build
          target: development
          build_type: Debug
          project: btserver
          version: 0.1
