name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Sonar
      uses: philips-software/sonar-scanner-action@v1.2.0
      with:
        token: ${{ secrets.SONARQUBE_TOKEN }}
        projectName: ConceptWorks - GHS - server
        projectKey: conceptworks.ghs.server
        url: https://sonarqube.ta.philips.com/
        enablePullRequestDecoration: true
