name: SonarQube

on:
  workflow_dispatch:

jobs:
  sonarqube:
    name: SonarQube
    runs-on: [self-hosted,  research]
    container: node:12-buster
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: philips-software/sonar-scanner-action@v1.2.0
        with:
          token: ${{ secrets.SONARQUBE_TOKEN }}
          projectName: ConceptWorks - GHS - server
          projectKey: conceptworks.ghs.server
          url: https://sonarqube.ta.philips.com/
          enablePullRequestDecoration: true
